//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sFinanciero.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalleTrans
    {
        public int id { get; set; }
        public int idTrans { get; set; }
        public string cuenta { get; set; }
        public Nullable<decimal> monto { get; set; }
        public string referencia { get; set; }
        public Nullable<int> idMoneda { get; set; }
    
        public virtual moneda moneda { get; set; }
        public virtual transaccion transaccion { get; set; }
    }
}
