//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sFinanciero.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class movimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public movimiento()
        {
            this.detalleMov = new HashSet<detalleMov>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fechaHora { get; set; }
        public Nullable<decimal> monto { get; set; }
        public Nullable<int> idCuenta { get; set; }
    
        public virtual cuenta cuenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalleMov> detalleMov { get; set; }
    }
}
