//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sFinanciero.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tarjeta
    {
        public int id { get; set; }
        public string nro { get; set; }
        public Nullable<System.DateTime> fecha_ini { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public string estado { get; set; }
        public Nullable<int> idTipoCuenta { get; set; }
        public Nullable<int> idTipoTarjeta { get; set; }
    
        public virtual tipoCuenta tipoCuenta { get; set; }
        public virtual tipoTarjeta tipoTarjeta { get; set; }
    }
}
