//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sFinanciero.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public transaccion()
        {
            this.detalleTrans = new HashSet<detalleTrans>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> fechaHora { get; set; }
        public string estado { get; set; }
        public Nullable<int> idOfi { get; set; }
        public Nullable<int> idCuenta1 { get; set; }
        public Nullable<int> idCuenta2 { get; set; }
        public Nullable<int> idBanco { get; set; }
    
        public virtual banco banco { get; set; }
        public virtual cuenta cuenta { get; set; }
        public virtual cuenta cuenta1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalleTrans> detalleTrans { get; set; }
        public virtual oficina oficina { get; set; }
    }
}
